check for installation of knative addon

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -25,6 +25,9 @@ stages:
   - name: KUBECTL_DOWNLOAD_URL
     value: https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl
     type: text
+  - name: CLUSTER_NAMESPACE
+    value: ${PROD_CLUSTER_NAMESPACE}
+    type: text
   jobs:
   - name: Build
     type: builder
@@ -50,6 +53,13 @@ stages:
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
       echo "APP_PORT=${APP_PORT}"
+
+      # Check for installation of Knative addon
+      KNATIVE_INSTALLED=$(ibmcloud cs cluster addons --cluster ${CLUSTER_NAMESPACE} --json | jq '.[].name?|select(. == "knative")')
+      if [-z "${KNATIVE_INSTALLED}"]; then
+          echo "Knative is required but is not installed in this cluster. Install the Knative add-on and retry. Note that the Knative add-on is not supported on lite clusters."
+          exit 1
+      fi
 
       # also run 'env' command to find all available env variables
       # or learn more about the available environment variables at:
