move knative check to deploy stage

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -25,9 +25,6 @@ stages:
   - name: KUBECTL_DOWNLOAD_URL
     value: https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl
     type: text
-  - name: CLUSTER_NAMESPACE
-    value: ${PROD_CLUSTER_NAMESPACE}
-    type: text
   jobs:
   - name: Build
     type: builder
@@ -53,13 +50,6 @@ stages:
       echo "BUILD_NUMBER=${BUILD_NUMBER}"
       echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
       echo "APP_PORT=${APP_PORT}"
-
-      # Check for installation of Knative addon
-      KNATIVE_INSTALLED=$(ibmcloud cs cluster addons --cluster ${CLUSTER_NAMESPACE} --json | jq '.[].name?|select(. == "knative")')
-      if [-z "${KNATIVE_INSTALLED}"]; then
-          echo "Knative is required but is not installed in this cluster. Install the Knative add-on and retry. Note that the Knative add-on is not supported on lite clusters."
-          exit 1
-      fi
 
       # also run 'env' command to find all available env variables
       # or learn more about the available environment variables at:
@@ -176,6 +166,14 @@ stages:
       IP_ADDR=$(ibmcloud cs workers ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep normal | head -n 1 | awk '{ print $2 }')
       if [ -z $IP_ADDR ]; then
           echo "$PIPELINE_KUBERNETES_CLUSTER_NAME not created or workers not ready"
+          exit 1
+      fi
+
+      # Check for installation of Knative addon
+      echo "Check Knative availability"
+      KNATIVE_INSTALLED=$(ibmcloud cs cluster addons --cluster ${PIPELINE_KUBERNETES_CLUSTER_NAME} --json | jq '.[].name?|select(. == "knative")')
+      if [ -z $KNATIVE_INSTALLED ]; then
+          echo "Knative is required but is not installed in this cluster. Install the Knative add-on and retry. Note that the Knative add-on is not supported on lite clusters."
           exit 1
       fi
 
