initial knative changes

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -1,227 +1,269 @@
 ---
 defaultBaseImageVersion: latest
-properties:
-- name: IBM_CLOUD_API_KEY
-  value: ${API_KEY}
-  type: secure
 stages:
-- name: BUILD
+- name: Build Stage
   inputs:
   - type: git
     branch: master
-    service: ${GIT_REPO}    
-  triggers:
-  - type: commit
+    service: ${REPO}
   properties:
   - name: IMAGE_NAME
-    value: ${APP_NAME}
+    value: ${IMAGE_NAME}
+    type: text
+  - name: KUBECTL_VERSION
+    value: v1.13.3
+    type: text
+  - name: KUBECTL_DOWNLOAD_URL
+    value: https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl
     type: text
   jobs:
-  - name: Fetch code
+  - name: Build
     type: builder
+    build_type: cr
     artifact_dir: ''
-    build_type: shell
-    script: |+
+    target:
+      region_id: ${REGION_ID}
+      api_key: ${API_KEY}
+    namespace: ${REGISTRY_NAMESPACE}
+    image_name: ${IMAGE_NAME}
+    script: |-
       #!/bin/bash
-      # set -x
 
-      # Git repo cloned at $WORKING_DIR, copy into $ARCHIVE_DIR
+      mkdir downloads
+      PATH="downloads:$PATH"
+      echo "kubectl version"
+      kubectl version --client
+
+      echo "Build environment variables:"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+
+      # also run 'env' command to find all available env variables
+      # or learn more about the available environment variables at:
+      # https://cloud.ibm.com/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      # To review or change build options use:
+      # ibmcloud cr build --help
+
+      echo "Checking registry namespace: ${REGISTRY_NAMESPACE}"
+      NS=$( ibmcloud cr namespaces | grep ${REGISTRY_NAMESPACE} ||: )
+      if [ -z "${NS}" ]; then
+          echo -e "Registry namespace ${REGISTRY_NAMESPACE} not found, creating it."
+          ibmcloud cr namespace-add ${REGISTRY_NAMESPACE}
+          echo -e "Registry namespace ${REGISTRY_NAMESPACE} created."
+      else
+          echo -e "Registry namespace ${REGISTRY_NAMESPACE} found."
+      fi
+
+      echo -e "Existing images in registry"
+
+      echo "=========================================================="
+      echo -e "BUILDING CONTAINER IMAGE: ${IMAGE_NAME}:${BUILD_NUMBER}"
+      set -x
+      ibmcloud cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER} .
+      ibmcloud cr image-tag ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER} \
+          ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:latest
+
+      set +x
+      ibmcloud cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER}
+
+      export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER"
+
+      echo "=========================================================="
+      echo "COPYING ARTIFACTS needed for deployment and testing (in particular build.properties)"
+
+      echo "Checking archive dir presence"
       mkdir -p $ARCHIVE_DIR
-      cp -R -n ./ $ARCHIVE_DIR/ || true
 
-      # Record git info
-      echo "GIT_URL=${GIT_URL}" >> $ARCHIVE_DIR/build.properties
-      echo "GIT_BRANCH=${GIT_BRANCH}" >> $ARCHIVE_DIR/build.properties
-      echo "GIT_COMMIT=${GIT_COMMIT}" >> $ARCHIVE_DIR/build.properties
-      echo "SOURCE_BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
+      # Persist env variables into a properties file (build.properties) so that all pipeline stages consuming this
+      # build as input and configured with an environment properties file valued 'build.properties'
+      # will be able to reuse the env variables in their job shell scripts.
+
+      # IMAGE information from build.properties is used in Helm Chart deployment to set the release name
+      echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
+      echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
+      # REGISTRY information from build.properties is used in Helm Chart deployment to generate cluster secret
+      echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
+      echo "File 'build.properties' created for passing env variables to subsequent pipeline jobs:"
       cat $ARCHIVE_DIR/build.properties
 
-      # check if doi is integrated in this toolchain
-      if jq -e '.services[] | select(.service_id=="draservicebroker")' _toolchain.json; then
-        # Record build information
-        ibmcloud login --apikey ${IBM_CLOUD_API_KEY} --no-region
-        ibmcloud doi publishbuildrecord --branch ${GIT_BRANCH} --repositoryurl ${GIT_URL} --commitid ${GIT_COMMIT} \
-          --buildnumber ${BUILD_NUMBER} --logicalappname ${IMAGE_NAME} --status pass
-      fi
-  - name: Unit Tests
-    type: tester
-    script: |-
-      #!/bin/bash
-      # set -x
-      if [ -f ./tests/run-tests.sh ]; then
-        source ./tests/run-tests.sh
-        RESULT=$?
-        if [ ! -z "${FILE_LOCATION}"]; then
-          if [ ${RESULT} -ne 0 ]; then STATUS=fail; else STATUS=pass; fi
-            if jq -e '.services[] | select(.service_id=="draservicebroker")' _toolchain.json; then
-              ibmcloud login --apikey ${IBM_CLOUD_API_KEY} --no-region
-              ibmcloud doi publishtestrecord --type unittest --buildnumber ${BUILD_NUMBER} --filelocation ${FILE_LOCATION} \
-                --buildnumber ${BUILD_NUMBER} --logicalappname ${IMAGE_NAME} --status ${STATUS}
-            fi
-          exit $RESULT
+      echo "Copy pipeline scripts along with the build"
+      # Copy scripts (incl. deploy scripts)
+      if [ -d ./scripts/ ]; then
+        if [ ! -d $ARCHIVE_DIR/scripts/ ]; then # no need to copy if working in ./ already
+          cp -r ./scripts/ $ARCHIVE_DIR/
         fi
-      else
-        echo "Test runner script not found: ./tests/run-tests.sh"
       fi
-- name: CONTAINERIZE
-  properties:
-  - name: buildprops
-    value: build.properties
-    type: file
-  - name: DOCKER_ROOT
-    value: .
-    type: text
-  - name: DOCKER_FILE
-    value: Dockerfile
-    type: text
-  - name: PIPELINE_IMAGE_URL
-    value: undefined
-    type: text
+
+      if  [[ -f post_build.sh ]]; then
+        chmod +x post_build.sh;
+        echo "executing the post_build script";
+        sh post_build.sh;
+      else
+        echo "the post_build script does not exist";
+      fi
+- name: Deploy Stage
   inputs:
   - type: job
-    stage: BUILD
-    job: Fetch code
-  triggers:
-  - type: stage
-  jobs:
-  - name: Check dockerfile
-    type: tester
-    script: |-
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-      # copy the script below into your app code repo (e.g. ./scripts/check_dockerfile.sh) and 'source' it from your pipeline job
-      #    source ./scripts/check_prebuild.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_dockerfile.sh")
-      # ------------------
-      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_dockerfile.sh
-
-      # This script lints Dockerfile.
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_dockerfile.sh")
-  - name: Check registry
-    type: builder
-    build_type: cr
-    artifact_dir: ''
-    target:
-      region_id: ${REGISTRY_REGION_ID}
-      api_key: ${API_KEY}
-    namespace: ${REGISTRY_NAMESPACE}
-    image_name: ${APP_NAME}
-    script: |-
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-      # copy the script below into your app code repo (e.g. ./scripts/check_registry.sh) and 'source' it from your pipeline job
-      #    source ./scripts/check_registry.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_registry.sh")
-      # ------------------
-      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_registry.sh
-
-      # This script checks presence of registry namespace.
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_registry.sh")
-  - name: Build container image
-    type: builder
-    build_type: cr
-    artifact_dir: output
-    target:
-      region_id: ${REGISTRY_REGION_ID}
-      api_key: ${API_KEY}
-    namespace: ${REGISTRY_NAMESPACE}
-    image_name: ${APP_NAME}
-    script: |
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-      # copy the script below into your app code repo (e.g. ./scripts/build_image.sh) and 'source' it from your pipeline job
-      #    source ./scripts/build_image.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/build_image.sh")
-      # ------------------
-      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/build_image.sh
-
-      # This script does build a Docker image into IBM Container Service private image registry.
-      # Minting image tag using format: BUILD_NUMBER-BRANCH-COMMIT_ID-TIMESTAMP
-      # Also copies information into a build.properties file, so they can be reused later on by other scripts (e.g. image url, chart name, ...)
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/build_image.sh")
-  - name: Check vulnerabilities
-    type: tester
-    test_type: vulnerabilityadvisor
-    use_image_from_build_input: true
-    fail_stage: false
-    target:
-      region_id: ${REGISTRY_REGION_ID}
-      api_key: ${API_KEY}
-    script: |
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-      # copy the script below into your app code repo (e.g. ./scripts/check_vulnerabilities.sh) and 'source' it from your pipeline job
-      #    source ./scripts/check_vulnerabilities.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh")
-      # ------------------
-      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh
-      # Check for vulnerabilities of built image using Vulnerability Advisor
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh")
-- name: DEPLOY
-  inputs:
-  - type: job
-    stage: CONTAINERIZE
-    job: Build container image
-  triggers:
-  - type: stage
+    stage: Build Stage
+    job: Build
   properties:
-  - name: buildprops
+  - name: buildProperties
     value: build.properties
     type: file
   - name: CLUSTER_NAMESPACE
-    value: ${PROD_CLUSTER_NAMESPACE}
+    value: ${CLUSTER_NAMESPACE}
     type: text
-  - name: DEPLOYMENT_FILE
-    value: deployment.yml
+  - name: SERVICE_FILE
+    value: service.yml
     type: text
-  - name: APP_URL
-    value: undefined
-    type: text  
+  triggers:
+  - type: stage
   jobs:
-  - name: Deploy to Kubernetes
+  - name: Deploy
     type: deployer
     target:
-      region_id: ${PROD_REGION_ID}
+      application: ${CF_APP}
       api_key: ${API_KEY}
-      kubernetes_cluster: ${PROD_CLUSTER_NAME}
-    script: |
-      #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-      # copy the script below into your app code repo (e.g. ./scripts/check_predeploy.sh) and 'source' it from your pipeline job
-      #    source ./scripts/check_predeploy_kubectl.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_and_deploy_kubectl.sh")
-      # ------------------
-      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_and_deploy_kubectl.sh
-
-      # This script checks the IBM Container Service cluster is ready, has a namespace configured with access to the private
-      # image registry (using an IBM Cloud API Key), perform a kubectl deploy of container image and check on outcome.
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_and_deploy_kubectl.sh")
-  - name: Check health
-    type: deployer
-    target:
-      region_id: ${PROD_REGION_ID}
-      resource_group: ${PROD_RESOURCE_GROUP}
-      api_key: ${API_KEY}
-      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+      region_id: ${REGION_ID}
+      kubernetes_cluster: ${KUBE_CLUSTER_NAME}
     script: |-
       #!/bin/bash
-      # uncomment to debug the script
-      # set -x
-      # copy the script below into your app code repo (e.g. ./scripts/check_health.sh) and 'source' it from your pipeline job
-      #    source ./scripts/check_health.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_health.sh")
-      # ------------------
-      # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_health.sh
-      # Check liveness and readiness probes to confirm application is healthy
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_health.sh")
+      export PATH="downloads:$PATH"
+
+      #View build properties
+      cat build.properties
+
+      echo "Check cluster availability"
+      IP_ADDR=$(ibmcloud cs workers ${PIPELINE_KUBERNETES_CLUSTER_NAME} | grep normal | head -n 1 | awk '{ print $2 }')
+      if [ -z $IP_ADDR ]; then
+          echo "$PIPELINE_KUBERNETES_CLUSTER_NAME not created or workers not ready"
+          exit 1
+      fi
+
+      echo "Configuring cluster namespace"
+      if kubectl get namespace ${CLUSTER_NAMESPACE}; then
+        echo -e "Namespace ${CLUSTER_NAMESPACE} found."
+      else
+        kubectl create namespace ${CLUSTER_NAMESPACE}
+        echo -e "Namespace ${CLUSTER_NAMESPACE} created."
+      fi
+
+      echo "Configuring cluster role binding"
+      if kubectl get clusterrolebinding kube-system:default; then
+        echo -e "Cluster role binding found."
+      else
+        kubectl create clusterrolebinding kube-system:default --clusterrole=cluster-admin --serviceaccount=kube-system:default
+        echo -e "Cluster role binding created."
+      fi
+
+
+      # Deploy the most recent revision of the specified image
+      sed -e "s/REGISTRY_URL/${REGISTRY_URL}/g; s/REGISTRY_NAMESPACE/${REGISTRY_NAMESPACE}/g; s/IMAGE_NAME/${IMAGE_NAME}/g; s/CLUSTER_NAMESPACE/${CLUSTER_NAMESPACE}/g s/APP_PORT/${APP_PORT}/g" ${SERVICE_FILE} | kubectl apply -f -
+
+
+      echo "Checking if application is ready..."
+      for ITERATION in {1..30}
+      do
+        sleep 3
+
+        kubectl get ksvc/${IMAGE_NAME} --output=custom-columns=DOMAIN:.status.conditions[*].status
+        SVC_STATUS_READY=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "True")' )
+        echo SVC_STATUS_READY=$SVC_STATUS_READY
+
+        SVC_STATUS_NOT_READY=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "False")' )
+        echo SVC_STATUS_NOT_READY=$SVC_STATUS_NOT_READY
+
+        SVC_STATUS_UNKNOWN=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "Unknown")' )
+        echo SVC_STATUS_UNKNOWN=$SVC_STATUS_UNKNOWN
+
+        if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
+          echo "Application not ready, retrying"
+        elif [ -n "$SVC_STATUS_READY" ]; then
+          echo "Application is ready"
+          break
+        else
+          echo "Application status unknown, retrying"
+        fi
+      done
+      echo "Application service details:"
+      kubectl describe ksvc/${IMAGE_NAME}
+      if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
+        echo "Application is not ready after waiting maximum time"
+        exit 1
+      fi
+
+      # Determine app url for polling from knative service
+      TEMP_URL=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status.url' )
+      echo "Application status URL: $TEMP_URL"
+      TEMP_URL=${TEMP_URL%\"} # remove end quote
+      TEMP_URL=${TEMP_URL#\"} # remove beginning quote
+      export APPLICATION_URL=$TEMP_URL
+      if [ -z "$APPLICATION_URL" ]; then
+        echo "Deploy failed, no URL found for knative service"
+        exit 1
+      fi
+      echo "Application is available"
+      echo "=========================================================="
+      echo -e "View the application health at: http://$APPLICATION_URL/health"
+
+      echo "export IP_ADDR=${IP_ADDR}" >> kube_vars.sh
+      echo "export PORT=${PORT}" >> kube_vars.sh
+- name: Health Stage
+  inputs:
+  - type: job
+    stage: Build Stage
+    job: Build
+  triggers:
+  - type: stage
+  permission:
+    execute: TOOLCHAIN_ADMINS
+  properties:
+  - name: CLUSTER_NAMESPACE
+    value: ${CLUSTER_NAMESPACE}
+    type: text
+  - name: buildProperties
+    value: build.properties
+    type: file
+  jobs:
+  - name: Test
+    type: deployer
+    deploy_type: kubernetes
+    target:
+      region_id: ${REGION_ID}
+      api_key: ${API_KEY}
+      kubernetes_cluster: ${KUBE_CLUSTER_NAME}
+    script: |-
+      export PATH="downloads:$PATH"
+      kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status.url'
+      TEMP_URL=$( kubectl get ksvc/${IMAGE_NAME} -o json | jq '.status.url' )
+      TEMP_URL=${TEMP_URL%\"} # remove end quote
+      TEMP_URL=${TEMP_URL#\"} # remove beginning quote
+      export APPLICATION_URL=$TEMP_URL
+
+      if [ "$(curl -is $APPLICATION_URL/health --connect-timeout 3 --max-time 5 --retry 2 --retry-max-time 30 | head -n 1 | grep 200)" != "" ]; then
+        echo "Successfully reached health endpoint at $APPLICATION_URL/health"
+        echo "====================================================================="
+      else
+        echo "Could not reach health endpoint: $APPLICATION_URL/health"
+        exit 1;
+      fi;
+  jobs:
+  - name: Test
+    type: tester
+    script: |-
+      #!/bin/sh
+      apk add --no-cache curl
+      if [ "$(curl -is http://{{manifest.host}}.{{manifest.domain}}/health  --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30 | head -n 1 | grep 200)" != "" ]; then
+        echo "Successfully reached health endpoint at http://{{manifest.host}}.{{manifest.domain}}/health"
+        echo "====================================================================="
+      else
+        echo "Could not reach health endpoint: http://{{manifest.host}}.{{manifest.domain}}/health"
+        exit 1;
+      fi;
+    test_type: customimage
+    docker_image: alpine
